standaloneservice:
  image: java:8
  working_dir: /app
  volumes:
    - ./standalone-service/build/libs:/app
  command: java -jar /app/standalone-service.jar --spring.datasource.url=jdbc:mysql://mysql/es-test
  ports:
    - "8080:8080"
  links:
    - mysql
  environment:
      EVENT_STORE_USER_ID:
      EVENT_STORE_PASSWORD:
      EVENT_STORE_URL:
      EVENT_STORE_STOMP_SERVER_HOST:
      EVENT_STORE_STOMP_SERVER_PORT:

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: es-test
  expose:
    - "3306"
  ports:
    - "3307:3306"