version: '3'
services:
  standaloneservice:
    build: ./
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/app
    depends_on:
      - mysql
    environment:
        EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
        EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate

  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
