zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.12.1
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

kafka:
  image: eventuateio/eventuateio-local-kafka:0.12.1
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

postgres:
  build: ./postgres
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: eventuate
    POSTGRES_PASSWORD: eventuate

cdcservice:
  extends:
    file: ../../eventuate-local/docker-compose-cdc-postgres.yml
    service: cdcservice
  links:
    - postgres
    - kafka
    - zookeeper

standaloneservice:
  extends:
    file: docker-compose-common.yml
    service: standaloneservice
  volumes:
    - ./build/libs:/app
  links:
    - postgres
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://172.17.0.1/eventuate
    SPRING_DATASOURCE_USERNAME: eventuate
    SPRING_DATASOURCE_PASSWORD: eventuate
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: 172.17.0.1:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: 172.17.0.1:2181

adminer:
  image: adminer
  ports:
    - 9080:8080