commandsideservice:
  image: java:8
  working_dir: /app
  volumes:
    - ./todo-command-service/build/libs:/app
  command: java -jar /app/todo-command-service.jar  --spring.datasource.url=jdbc:mysql://mysql/es-test
  ports:
    - "8081:8080"
  links:
    - mysql
  environment:
      EVENTUATE_API_KEY_ID:
      EVENTUATE_API_KEY_SECRET:

querysideservice:
  image: java:8
  working_dir: /app
  volumes:
    - ./todo-query-service/build/libs:/app
  command: java -jar /app/todo-query-service.jar --spring.datasource.url=jdbc:mysql://mysql/es-test
  ports:
    - "8082:8080"
  links:
    - mysql
  environment:
      EVENTUATE_API_KEY_ID:
      EVENTUATE_API_KEY_SECRET:

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: es-test
  expose:
    - "3306"
  ports:
    - "3307:3306"