version: '3'
services:
  commandsideservice:
    build: ./todo-service/
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
      EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate

  querysideservice:
    build: ./todo-view-service/
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
      EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate

  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw


